telegram_bot_token: 5082785360:AAFlhP6gC6gQEKEAACxbtzvuzYW4L6IdB_Y

LIBSQL_URL: "libsql://six-hono-testlibsql.aws-ap-northeast-1.turso.io"
LIBSQL_TOKEN: "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NzEwMjA1NDAsImlkIjoiZTk2OTRlYWMtNTYzMi00ZDlkLTkyOWEtNTM0YjY0NDBjZTg2IiwicmlkIjoiYzFhMzZhOTctY2FhZS00MDI3LTg3NDgtOTM2OTcxMGFiMDlhIn0.m2ib_i6KqU08dl-tZrsau2QoQA08R-rM4OUqIvNdhHbIm_ro6N3QD54gP0bTV2kYF7nvTeXU9GPlO2hbN_lCBA"

turso_token: "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJoMzhiYWdhcEVmR2lKd3E5bHRidml3In0.OUHj4wgUMqWV1YdZ70a35R_niv52Qkk3YY7JpGy0GzD3H0L-DnK5VVZ9aWo4AkCec20aOl0skPF9_0wEJfLqBA"
